version: '2'

services:
  voltronic-mqtt:

    build: .
    #image: bushrangers/ha-voltronic-mqtt

    container_name: voltronic-mqtt

    privileged: true
    restart: always

    volumes:
        - ./config/:/etc/inverter/

    devices:
    #  - "/dev/mem:/dev/mem"

    # USB Port Mapping
      - /dev/bus/usb:/dev/bus/usb:rwm
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm
      - /dev/ttyUSB1:/dev/ttyUSB1:rwm

    # Serial Port Mapping...
      - /dev/ttyS0:/dev/ttyS0
      - /dev/ttyS1:/dev/ttyS1
      - /dev/ttyS2:/dev/ttyS2
