version: '3'

services:
  inverter:

    # Uncomment for nedkelly's dockerhub image We're now (finally) supporting Multi-Arch builds (via Github actions) on Docker Hub!
    # image: bushrangers/ha-voltronic-mqtt

    # Uncomment if you want to build your own local version.
    build:
      context: .
      dockerfile: Dockerfile.dev


    container_name: inverter

    privileged: true
    restart: always

    volumes:
        - ./config/:/etc/inverter/

    devices:
    #  - "/dev/mem:/dev/mem"

    # USB Port Mapping
      - /dev/bus/usb:/dev/bus/usb:rwm
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm
      - /dev/ttyUSB1:/dev/ttyUSB1:rwm

    # Serial Port Mapping...
      - /dev/ttyS0:/dev/ttyS0
      - /dev/ttyS1:/dev/ttyS1
      - /dev/ttyS2:/dev/ttyS2

  # uncomment to use auto-update of nedkellys dockerhub images as he releases new versions...
  # watchtower:
  # Please see the following for configuration options:
  # https://containrrr.github.io/watchtower/container-selection/
  #  image: containrrr/watchtower
  #  container_name: watchtower
  #
  #  restart: always
  #  privileged: true
  #
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #
  #  command: --interval 500
